name: Run Jest Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: |
        npm ci
        npm install --save-dev jest

    - name: Fix Jest Permissions
      run: chmod +x node_modules/.bin/jest

    - name: Run Jest tests
      run: CI=true npx jest
